version: "3"

services:
  signoz:
    image: signoz-community:${SIGNOZ_COMMUNITY_TAG:-local}
    environment:
      - SIGNOZ_USER_ROOT_ENABLED=${SIGNOZ_USER_ROOT_ENABLED:-false}
      - SIGNOZ_USER_ROOT_EMAIL=${SIGNOZ_USER_ROOT_EMAIL:-}
      - SIGNOZ_USER_ROOT_PASSWORD=${SIGNOZ_USER_ROOT_PASSWORD:-}
      - SIGNOZ_USER_ROOT_ORG_NAME=${SIGNOZ_USER_ROOT_ORG_NAME:-default}
      - SIGNOZ_ENTRA_SSO_ENABLED=${SIGNOZ_ENTRA_SSO_ENABLED:-false}
      - SIGNOZ_ENTRA_TENANT_ID=${SIGNOZ_ENTRA_TENANT_ID}
      - SIGNOZ_ENTRA_CLIENT_ID=${SIGNOZ_ENTRA_CLIENT_ID}
      - SIGNOZ_ENTRA_CLIENT_SECRET=${SIGNOZ_ENTRA_CLIENT_SECRET}
      - SIGNOZ_ENTRA_DOMAIN=${SIGNOZ_ENTRA_DOMAIN}
      - SIGNOZ_ENTRA_ADMIN_GROUP_ID=${SIGNOZ_ENTRA_ADMIN_GROUP_ID:-}
      - SIGNOZ_ENTRA_EDITOR_GROUP_ID=${SIGNOZ_ENTRA_EDITOR_GROUP_ID:-}
      - SIGNOZ_ENTRA_DEFAULT_ROLE=${SIGNOZ_ENTRA_DEFAULT_ROLE:-VIEWER}
